runtime: php8 # bisa sesuaikan php versionnya
env_variables:
  APP_KEY: base64:7U1r+n8iXFpcwoR9Tj0HMtAGbsFKvclnGF1O2R6DDN4= # copy output dari key generate kesini
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie